### ISSUE TITLE
Ошибка на проде [ SendStream.error ]

### ISSUE THREAD

**Issue by pofigizm** [shri-2015-org/666#141]
Появилась только один раз.

RangeNotSatisfiableError: Range Not Satisfiable
    at SendStream.error (/root/node_modules/express/node_modules/send/index.js:245:31)
    at SendStream.send (/root/node_modules/express/node_modules/send/index.js:564:19)
    at /root/node_modules/express/node_modules/send/index.js:669:12
    at FSReqWrap.oncomplete (fs.js:95:15)

**Comment by pofigizm** [comment]
После ошибки все продолжает работать нормально. Надо разбираться если будет повторяться.
